-- SIFAP 2.0 - esquema inicial do recorte 001 (geracao mensal da folha)
-- Mapeamento conforme 02-modern-spec/adr/ADR-001-mapeamento-adabas-postgresql.md
-- Nenhuma coluna deriva de ISN (PAYMENT.ddm:181-182).

-- BENEFIC (FNR 150)
CREATE TABLE beneficiary (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf                    VARCHAR(11)  NOT NULL,
    full_name              VARCHAR(60)  NOT NULL,
    birth_date             DATE         NOT NULL,
    status                 VARCHAR(14)  NOT NULL,
    program_code           VARCHAR(4)   NOT NULL,
    family_income          NUMERIC(11,2) NOT NULL,
    active_dependents      SMALLINT     NOT NULL DEFAULT 0,
    region_code            SMALLINT     NOT NULL,
    federative_unit        CHAR(2),
    nis                    BIGINT,
    documentation_complete BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_beneficiary_cpf UNIQUE (cpf),
    CONSTRAINT ck_beneficiary_status
        CHECK (status IN ('ACTIVE','SUSPENDED','CANCELED','INACTIVE','DISCONNECTED')),
    CONSTRAINT ck_beneficiary_dependents CHECK (active_dependents >= 0)
);

-- REQ-003 - a folha varre somente ativos, na ordem de CPF.
CREATE INDEX ix_beneficiary_status_cpf ON beneficiary (status, cpf);

-- SOCPROG (FNR 151) - tabela de parametros, ~45 registros.
CREATE TABLE social_program (
    code                   VARCHAR(4)   NOT NULL PRIMARY KEY,
    name                   VARCHAR(60)  NOT NULL,
    type                   VARCHAR(20)  NOT NULL,
    status                 VARCHAR(10)  NOT NULL,
    individual_base_amount NUMERIC(9,2) NOT NULL,
    adjustment_factor      NUMERIC(7,4) NOT NULL DEFAULT 0,
    maximum_income         NUMERIC(9,2) NOT NULL DEFAULT 0,
    minimum_age            SMALLINT     NOT NULL DEFAULT 0,
    maximum_age            SMALLINT     NOT NULL DEFAULT 0,
    eligibility_code       VARCHAR(5),
    applicable_discounts   VARCHAR(64),
    CONSTRAINT ck_social_program_type
        CHECK (type IN ('ASSISTANCE','SOCIAL_SECURITY','EMPLOYMENT')),
    CONSTRAINT ck_social_program_status CHECK (status IN ('ACTIVE','INACTIVE','ENDED'))
);

-- PAYMENT (FNR 152)
CREATE TABLE payment (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf              VARCHAR(11)   NOT NULL,
    program_code     VARCHAR(4)    NOT NULL,
    reference_period INTEGER       NOT NULL,
    gross_amount     NUMERIC(11,2) NOT NULL,
    total_discount   NUMERIC(11,2) NOT NULL,
    net_amount       NUMERIC(11,2) NOT NULL,
    status           VARCHAR(12)   NOT NULL,
    kind             VARCHAR(12)   NOT NULL,
    generation_date  DATE          NOT NULL,
    created_at       TIMESTAMP     NOT NULL,
    CONSTRAINT ck_payment_amounts_non_negative
        CHECK (gross_amount >= 0 AND total_discount >= 0 AND net_amount >= 0),
    CONSTRAINT ck_payment_period CHECK (reference_period BETWEEN 199701 AND 999912)
);

-- REQ-002 - traduz o superdescritor SUPER-CPF-PERIOD (PAYMENT.ddm:159-160).
-- Garante no banco a invariante que BATCHPGT.NSP:295-301 verifica em codigo.
CREATE UNIQUE INDEX uk_payment_cpf_period ON payment (cpf, reference_period);

CREATE INDEX ix_payment_period ON payment (reference_period);
