-- REQ-004 - trilha de auditoria (AUDIT.ddm, FNR 153).
-- Base legal: IN-TCU 63/2010. Retencao minima de 10 anos (Lei 8.159, art. 14).
-- AUDIT.ddm:13-14 - registro imutavel: nao ha UPDATE nem DELETE nesta tabela.

CREATE TABLE audit_trail (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      VARCHAR(16)  NOT NULL,
    entity_type VARCHAR(4)   NOT NULL,
    entity_id   VARCHAR(15)  NOT NULL,
    -- REQ-031 - somente o documento mascarado. O legado grava o CPF completo
    -- em NUM-CPF-AFFECTED (CCAUDIT.NSC:97).
    masked_cpf  VARCHAR(14),
    module_name VARCHAR(40)  NOT NULL,
    description VARCHAR(200),
    occurred_at TIMESTAMP    NOT NULL,
    CONSTRAINT ck_audit_action CHECK (action IN (
        'INSERT','UPDATE','DELETE','QUERY','LOGIN','LOGOUT',
        'BATCH','ERROR','AUTHORIZATION','REJECTION'))
);

-- AUDIT.ddm:18 - consultas pesadas devem usar o superdescritor S2 (entidade + data).
CREATE INDEX ix_audit_entity_date ON audit_trail (entity_type, entity_id, occurred_at);
CREATE INDEX ix_audit_date_action ON audit_trail (occurred_at, action);
